### ISSUE TITLE
[Bug]: Marked as Server unsupported but Chipped needs it on servers

### ISSUE THREAD

**Issue by xR4YM0ND** [terrarium-earth/Athena#11]
### Bug Description

Pls change the tag for servers to supported on modrinth.

People who want to download our serverpack cant run the pack cause athena isnt marked for servers

### Version

3.1.1

### Mod Loader Version

0.14.25

### Mod Loader

Fabric

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by xR4YM0ND** [comment]
Any updates on this?

Should be just a tag setting in modrinth

**Comment by ThatGravyBoat** [comment]
I am not marking it as supported on modrinth as it does not do anything on a server and would make people believe they need it on a server when it does not need to be, there is a comment on the fabric loader github for client side dependencies and there is apparently something in the works.
