### ISSUE TITLE
[Feature Request]: Java Properties (OptiFine) support

### ISSUE THREAD

**Issue by FarestR06** [terrarium-earth/Athena#16]
### Is your feature request related to a problem?

There's no way to have connected textures that are compatible with most packs unless you have OptiFine. However, its rewrites make it a pain to use with other mods.

### Solution(s)

The custom CTM used in Athena should have support for OptiFine's format

### Describe alternatives you've considered

A mod called Continuity does that on fabric, so it is possible. However, it relies heavily on the Indigo renderer, so it's stuck on fabric and quilt.

### Mod Version

4.0.0

### Mod Loader Version

1.21: 21.0.43-BETA

### Mod Loader

NeoForge

### Additional context

Honestly, I'm just asking because there's no proper OF CTM support on NeoForge.

**Comment by CodexAdrian** [comment]
We have no plans to support the Optifine format. if you'd like to use optifine resource packs on forge, please use
[Connectedness](https://www.curseforge.com/minecraft/mc-mods/connectedness)
