### ISSUE TITLE
[Bug]: [Fabric] Athena 3.1.1 is marked for Forge 1.20.1 on Modrinth

### ISSUE THREAD

**Issue by Amronos** [terrarium-earth/Athena#8]
### Bug Description

https://modrinth.com/mod/athena-ctm/version/Jy8DnzcO

The above version of the mod is marked as Forge 1.20.1 while it is a fabric version.

### How to Reproduce?

1. Go to this [version](https://modrinth.com/mod/athena-ctm/version/Jy8DnzcO) of the mod.
2. Observe that the loader for the version is marked as Forge 1.20.1.

### Expected Behavior

The loader for that version of the mod should have been marked as Fabric 1.20.1

### Version

3.1.1

### Mod Loader Version

1.20.1

### Mod Loader

Forge

### Code of Conduct

- [X] I have searched the issue tracker and confirmed that the issue has not been reported
- [X] I have checked the FAQ (if one is present) and my issue is not listed
- [X] I have verified that I am using the latest version of the mod
- [X] I have verified that I have installed all the required dependencies for the mod
- [X] I have verified that I do not have Optifine installed. We will close issues if we detect Optifine is in your pack. We cannot fix Optifine issues. Please do not report issues with Optifine present.

**Comment by CodexAdrian** [comment]
Fixed
